src/CoreMVCBasicExample/Controllers/AuthController.cs
using CoreMVCBasicExample.Models;
using Microsoft.AspNetCore.Http.Authentication;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace CoreMVCBasicExample.Controllers
{
    //you can use this controller to create your own authentication methods. I ussualy use it to logout too
    public class AuthController : Controller
    {
        public CoreMVCBasicExampleDBContext db;

        public AuthController(CoreMVCBasicExampleDBContext context)
        {
            db = context;
        }
        public async void Authentication(Users user)
        {
            var claims = new List<Claim>();
            claims.Add(new Claim(ClaimTypes.Name, user.Name, ClaimValueTypes.String));
            claims.Add(new Claim(ClaimTypes.Role, db.Permissions.Where(x => x.Id == user.PermissionId).Single().PermissionName, ClaimValueTypes.String));

            var userIdentity = new ClaimsIdentity("SecureLogin");
            userIdentity.AddClaims(claims);
            var userPrincipal = new ClaimsPrincipal(userIdentity);

            await HttpContext.Authentication.SignInAsync("Cookie", userPrincipal,
                        new AuthenticationProperties
                        {
                            ExpiresUtc = DateTime.UtcNow.AddMinutes(20),
                            IsPersistent = false,
                            AllowRefresh = false
                        });
        }

        public IActionResult Logout()
        {
            //Since we can't remove cookies we just expires it
            HttpContext.Authentication.SignOutAsync("Cookie", new AuthenticationProperties
            {
                ExpiresUtc = DateTime.UtcNow.AddDays(-1d),
                IsPersistent = false,
                AllowRefresh = false
            });
            return RedirectToAction("Index", "Home");
        }
    }
}

src/CoreMVCBasicExample/Controllers/UsersController.cs
using System;
using System.Linq;
using CoreMVCBasicExample.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CoreMVCBasicExample.Useful;
using Microsoft.AspNetCore.Authorization;
using System.Threading.Tasks;
using CoreMVCBasicExample.Handlers;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
namespace CoreMVCBasicExample.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        public CoreMVCBasicExampleDBContext db;
        IAuthorizationService authService;
        public UsersController(CoreMVCBasicExampleDBContext context, IAuthorizationService authorizationService)
        {
            db = context;
            authService = authorizationService;
        }

        // GET: Users
        public IActionResult Index()
        {
            var users = db.Users.Include(u => u.Permission);
            return View(users.ToList());
        }

        // GET: Users/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }
            Users users = db.Users.Where(x => x.Id == id).SingleOrDefault();
            if (users == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(users);
        }

        // GET: Users/Create
        public async Task<IActionResult> Create()
        {
            Pages page = db.Pages.Where(x => x.PageName == "Users - Create" ).SingleOrDefault();
            page.PagesPermissions = db.PagesPermissions.Where(x => x.PageId == page.Id).ToList();
            for (int i = 0; i < page.PagesPermissions.Count; i++)
                page.PagesPermissions.ElementAt(i).Permission = db.Permissions.Where(x => x.Id == page.PagesPermissions.ElementAt(i).PermissionId).SingleOrDefault();

            if (page == null)
            {
                return new NotFoundResult();
            }

            if (await authService.AuthorizeAsync(User, page, new PageRequirement()))
            {
                ViewBag.PermissionId = new SelectList(db.Permissions, "Id", "PermissionName");
                return View();
            }
            else
            {
                return new ChallengeResult();
            }

        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(string UserName, string Name, string LastName, string Password, int PermissionId)
        {
            MyConvert convert = new MyConvert();
            Users user = new Users
            {
                UserName = UserName,
                Name = Name,
                LastName = LastName,
                Password = convert.ToMD5(Password),
                PermissionId = PermissionId
            };
            if (ModelState.IsValid)
            {
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PermissionId = new SelectList(db.Permissions, "Id", "PermissionName", user.PermissionId);
            return View(user);
        }

        // GET: Users/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }
            Users users = db.Users.Where(x => x.Id == id).SingleOrDefault();
            if (users == null)
            {
                return RedirectToAction("Error", "Home");
            }
            ViewBag.PermissionId = new SelectList(db.Permissions, "Id", "PermissionName", users.PermissionId);
            return View(users);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int Id, string UserName, string Name, string LastName, int PermissionId)
        {
            Users user = new Users
            {
                Id = Id,
                UserName = UserName,
                Name = Name,
                LastName = LastName,
                PermissionId = PermissionId
            };

            if (ModelState.IsValid)

            {
                
                var entry = db.Entry(user);
                entry.State = EntityState.Modified;
                entry.Property("Password").IsModified = false; //you can use this to not update a specific property

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PermissionId = new SelectList(db.Permissions, "Id", "PermissionName", user.PermissionId);
            return View(user);
        }

        // GET: Users/Delete/5
        public IActionResult Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    return RedirectToAction("Error", "Home");
                }
                Users users = db.Users.Where(x => x.Id == id).SingleOrDefault();
                if (users == null)
                {
                    return RedirectToAction("Error", "Home");
                }
                return View(users);
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = "Please, try again later or send the following code to our support:" + e.HResult;
                return View("Index");
            }
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Users users = db.Users.Where(x => x.Id == id).Single();
            db.Users.Remove(users);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/CoreMVCBasicExample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreMVCBasicExample</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    @if (ViewBag.ErrorMessage != null)
    {
        <div class="alert alert-danger alert-dismissible" role="alert" style="margin-top: 100px;">
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
            </button>
            <strong>it seems that something went wrong. </strong> <br /><br />@Html.Raw(@ViewBag.ErrorMessage)
        </div>
    }
    @if (ViewBag.SuccessMessage != null)
    {
        <div class="alert alert-success alert-dismissible" role="alert" style="margin-top: 100px;">
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
            </button>
            <strong>Success! </strong><br /><br />@Html.Raw(@ViewBag.SuccessMessage)
        </div>
    }
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CoreMVCBasicExample</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>

                    @if (!User.Identities.Any(u => u.IsAuthenticated))
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="Login">Login</a></li>
                    }
                    else if (User.IsInRole("Admin"))
                    {
                        <li><a asp-area="" asp-controller="Users" asp-action="Index">Users</a></li>
                        <li><a asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a></li>
                    }
                    else if (User.IsInRole("User"))
                    {
                        <li><a asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a></li>
                    }
                    @*else if(User.Identity.AuthenticationType())
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="Login">Login</a></li>
                        <h1>
                            Hello @User.Identities.First(
      u => u.IsAuthenticated &&
      u.HasClaim(c => c.Type == ClaimTypes.Name)).FindFirst(ClaimTypes.Name).Value
                        </h1>
                    }*@

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - CoreMVCBasicExample</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>